### ISSUE TITLE
如何修改字体?

### ISSUE THREAD

**Issue by leviathan0992** [chunqiuyiyu/hexo-theme-polk#5]

**Comment by chunqiuyiyu** [comment]
@Leviathan1995  `source/css/style.styl` 中，如下代码：
```css
html, body, .container {
  height: 100%;
  font-family: Hiragino Sans GB, Microsoft YaHei, WenQuanYi, Airal, sans-serif;
  color: #444;
}
```
里面 font-family 属性设置了主题全局的字体，你可以更改值为自己喜欢的字体。
